#VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = no # Enable Bootmagic Lite

TD_LSFT_CAPSLOCK_ENABLE = no
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_DEFAULTACTIONS_ENABLE = yes

DEBOUNCE_TYPE = sym_defer_pk
DEBOUNCE = 20
